### PR TITLE
Fix data races in the provider

### PR DESCRIPTION
**Pull request by dgregoire**
Fixes two data races between the go routines in `run()` and the API reading them.

* `SessionStatus` being extracted by direct access
* `LastError` was also being accessed directly

Small refactor to have that state held inside the `run()` main loop and communicated with a channel.

### CODE REVIEW

**Comment by dgregoire** [comment]
Also added race detection to the GitHub action workflow.

**Review by ccapurso — APPROVED** [review]
Looks good, thanks!

**Review by manish-hashicorp — APPROVED** [review]
Interesting way to fix it. We just have to make sure that the run loop doesn't get blocked on anything. Otherwise, `SessionStatus()` and `LastError()` will be blocked.

**Comment by dgregoire** [comment]
> interesting way to fix it. We just have to make sure that the run loop doesn't get blocked on anything. Otherwise, `SessionStatus()` and `LastError()` will be blocked.

There's the `actions` case that might get blocked by the `token()` function that does not take a context: should wrap the whole block inside a go routine or give it a context with a timeout. We can do this subsequently.

**Pull request merged**
