### PR TITLE
CC-7032: Support for updating the provider's configuration

### PR DESCRIPTION
**Pull request by mkam**
### :hammer_and_wrench: Description
Adds support for updating the SCADA provider configuration. We plan to create a SCADA provider in our code and then later update the config to set the the Resource and HCPConfig when those values are known.

### :link: External Links
- https://hashicorp.atlassian.net/browse/CC-7032

### :+1: Definition of Done
- [X] Tests added?
- [ ] Docs updated?

### CODE REVIEW

**Comment by mkam** [comment]
Marking this as a draft since we're discussing some alternative options to this PR.

**Comment by mkam** [comment]
Marked this PR as ready to review again! We aren't able to replace the SCADA provider in our use case, so we will still need to be able to update this configuration after initialization. I've added a mutex around accessing the config to address some previous concerns with updating.

**Review by jasonpilz — APPROVED** [review]
LGTM. I'd like @dgregoire to take a 👀 as well though

**Comment by dgregoire** [comment]
I've looked at this too, we have an internal discussion thread going.

**Pull request merged**
